name: Deploy Shell App to Kubernetes

on:
  push:
    branches: [main]  # change if your deploy branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    env:
      IMAGE_NAME: hyndav/shell-app
      TAG: latest

    steps:

      - name: Checkout shell-app
        uses: actions/checkout@v3
        with:
          path: shell-app

      - name: Checkout helm-deployment
        uses: actions/checkout@v3
        with:
          repository: HyndaviParapatakam/shell-app-helm
          token: ${{ secrets.GITHUB_TOKEN }}
          path: shell-app-helm


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t $IMAGE_NAME:$TAG -f shell-app/Dockerfile shell-app
          docker push $IMAGE_NAME:$TAG

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > kubeconfig
          echo "KUBECONFIG=$PWD/kubeconfig" >> $GITHUB_ENV

      - name: Helm Upgrade
        run: |
           helm upgrade --install shell-app shell-app-helm \
            --set image.tag=$TAG \
            --set dummy=$(date +%s)
