name: Deploy Shell App to Kubernetes

on:
  push:
    branches: [main]  # change if your deploy branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: hyndav/shell-app
      TAG: latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t $IMAGE_NAME:$TAG .
          docker push $IMAGE_NAME:$TAG

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig >> $GITHUB_ENV

      - name: Helm Upgrade
        run: |
          helm upgrade --install shell-app ../../helm-deployment/shell-app-helm --set image.tag=$TAG --set dummy=$(date +%s)
